# Site
subtitle: Un tema para Hexo
description: Un tema para Hexo

# Pagination
pagination_dir: pagina

# Date / time format
post_date_format: D [de] MMMM [del] YYYY

# Directory
archive_dir: archivo
